name = "skybeings-backend"
main = "src/worker-index.js"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env", "no_handle_cross_request_promise_resolution"]

[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://skybeings.in,https://www.skybeings.in,https://skybeing.pages.dev"
UPLOAD_PROVIDER = "cloudinary"
JWT_EXPIRY = "1d"
CLOUDFLARE_R2_ENDPOINT = "https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
CLOUDFLARE_R2_BUCKET_NAME = "<YOUR_BUCKET_NAME>"
CLOUDFLARE_R2_PUBLIC_URL = "https://<YOUR_BUCKET_PUBLIC_URL>"
CLOUDFLARE_R2_ACCESS_KEY_ID = "<YOUR_R2_ACCESS_KEY_ID>"
CLOUDFLARE_R2_SECRET_ACCESS_KEY = "<YOUR_R2_SECRET_ACCESS_KEY>"


